### ISSUE TITLE
[Feature] Make Hero Section Prototype

### ISSUE THREAD

**Issue by juancwu** [LaurierHawkHacks/Landing#104]

**Comment by teoh4770** [comment]
![Screenshot 2024-02-20 at 10 10 56 AM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/8f905a2f-30a6-4b32-a024-2fd27c47c451)

![Screenshot 2024-02-20 at 10 11 54 AM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/4e81fb39-21f0-470d-85d2-006c28006aaa)

**Comment by teoh4770** [comment]
The design file:
https://www.figma.com/file/VvdbDssP3ZjSlRxkc6F9YK/hawkhack-my-own-draft?type=design&node-id=0%3A1&mode=design&t=HTEZxbX2ztH1n6v7-1

**Comment by juancwu** [comment]
I am a bit paranoid that others can just come here and copy the Figma assets that our design team work hard on. So I will avoid putting any Figma links....

@teoh4770

**Comment by teoh4770** [comment]
Alright, let me do that right now
