### ISSUE TITLE
[Bug/Enhancement] Update Font Sizes For the Title & Subtitle in Hero Section

### ISSUE THREAD

**Issue by juancwu** [LaurierHawkHacks/Landing#127]
Currently the font sizes don't exactly match the figma design making the dynamic or the look of it weird (at least to me).

**Comment by teoh4770** [comment]
Yes it is weird imo. Thanks for pointing out.
Small question: do you think making the font size scale dynamically is a good idea? @juancwu

**Comment by juancwu** [comment]
> Yes it is weird imo. Thanks for pointing out.
> Small question: do you think making the font size scale dynamically is a good idea? @juancwu 

We should make the font smaller as the device width decreases but currently, I don't think the values for the desktop is not working out. Specifically the HawkHacks title. We should either maintain the ratio between the title and subtitle or have the same values.

The subtitle is 32px(2rem) but the title is not nearly close to the original size in Figma 110px(6.875rem). We have the font sizes configured in tailwind already so it should be an easy fix.

I think the breakpoint `xl`  for the title should be `lg` instead of use `text-8.5xl`. It is really big but it also makes the hero section look better.

As I said, I think we should keep the ratio when decreasing the font sizes if the current size on Figma seems way to big.

**Comment by teoh4770** [comment]
Alright, just focusing on fixing the desktop font for now...Can I handle it @juancwu

**Comment by juancwu** [comment]
> Alright, just focusing on fixing the desktop font for now...Can I handle this issue @juancwu ?

Sure, go for it
