### ISSUE TITLE
[Fix] Refactor Team Section

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#136]

**Comment by teoh4770** [comment]
![Screenshot 2024-03-19 at 8 10 35 PM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/e677f48e-0269-4fa5-a79e-5001c7e1e3e8)
do you think having more padding is better in this case?

![Screenshot 2024-03-19 at 8 11 29 PM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/b8b66735-f058-4cbc-b7b2-6e66c273a6e1)
you also think circle is better in this case right?

**Comment by teoh4770** [comment]
I will tackle this issue, if I could know what the requirements of this issue is @aidantrabs
