### ISSUE TITLE
[Bug] Meet the Team SVG header blurry on smaller screens

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#139]

**Comment by teoh4770** [comment]
![image](https://github.com/LaurierHawkHacks/Landing/assets/98545971/94599776-49c1-4331-9ee5-2985aba4242c)


 yeah change all the images to the same shape as lg screens; also, make each subsection heading (development, admin etc) a lil larger than the names

**Comment by teoh4770** [comment]
update the balloon image as well
