### ISSUE TITLE
[Feature] Add loading animation before page renders 

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#144]
- Looks terrible when it takes a sec to load in the svgs, so add a delay page with some loading animation to allow rendering before displaying

**Comment by teoh4770** [comment]
@GabeDiniz you initially tried to handle this issue before right? Can you handle it?

**Comment by GabeDiniz** [comment]
@teoh4770 oui oui I'll take it
![KravatieGIF](https://github.com/LaurierHawkHacks/Landing/assets/55710093/8072cc9b-c84c-422e-a523-a071997ecec5)

**Comment by teoh4770** [comment]
Bro I can't 🤣
