### ISSUE TITLE
[Bug] Fix the hero section

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#177]
- Also need to readjust the "Meet the Team" title on mobile again (big sorry)

**Comment by teoh4770** [comment]
![EfneDghXgAAbjH7.jpg](https://github.com/LaurierHawkHacks/Landing/assets/98545971/392e30a3-2123-4858-8168-04d136ba3e58)

**Comment by teoh4770** [comment]
I got you
