### ISSUE TITLE
[Fix] Edit dates in stats

### ISSUE THREAD

**Issue by norachams** [LaurierHawkHacks/Landing#197]

**Comment by teoh4770** [comment]
it is not 5th - 7th?

**Comment by norachams** [comment]
> it is not 5th - 7th?

was it not changed to may 17 to may 19?

**Comment by teoh4770** [comment]
I didn't know, thx

**Comment by teoh4770** [comment]
![Screenshot 2024-03-29 at 9 11 44 PM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/3c0b606d-107d-4f24-8fd0-3d0445bc67b5)

like this? @norachams

**Comment by aidantrabs** [comment]
> ![Screenshot 2024-03-29 at 9 11 44 PM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/3c0b606d-107d-4f24-8fd0-3d0445bc67b5)
> 
> 
> 
> like this? @norachams 

that's right
