### ISSUE TITLE
[Enhancement] smooth scrolling issue

### ISSUE THREAD

**Issue by teoh4770** [LaurierHawkHacks/Landing#209]
Not sure if this is an issue, but since our landing page right now is so large, smooth scrolling takes slightly a bit time.

![Screenshot 2024-03-31 at 11 09 33 AM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/1c9d2901-84d1-4018-bd17-614807322499)

Propose: only keep smooth scrolling at the "go to top" button
Note: can also make our logo in the navbar triggers"go to top" event when clicked (i find myself doing this all the time, don't know how other's think?)

**Comment by GabeDiniz** [comment]
I really like this "logo in the navbar triggers go to top event".
That's a great idea Chee

**Comment by SherRao** [comment]
Not really a biggie, closing
