### ISSUE TITLE
[Bug] Fix FAQ section issues

### ISSUE THREAD

**Issue by GabeDiniz** [LaurierHawkHacks/Landing#280]
Website FAQ can be [found here](https://www.notion.so/hawkhacks/Website-FAQ-5f4cdf35cff34b4ebd8a8e15606f1128).

- [x] "Do I need to know how to code like some sort of crazy hacker?" is a repeat of "Who can attend? Do I need to be a crazy W-skilled programmer?". We should remove the first.
- [x] "When do applications open?" has the wrong response. It should only contain Part A from the Notion.
- [x] Paragraph spacing for the COVID question is WAYYY too large.
- [x] Update "Why should I come to HawkHacks specifically? / What types of things can I expect at HawkHacks?" with the correct response. Ask naush which of the two versions to use from the Notion.
- [x] Add the "Preparation" section with all its questions.
- [x] Double check all questions are copy-pasted from the Notion properly - a lot have changed after the fact.

**Comment by SherRao** [comment]
Edited your initial comment with 4 todos
