### ISSUE TITLE
[Fix] Anchor for Meet the Team is WAY too high up

### ISSUE THREAD

**Issue by SherRao** [LaurierHawkHacks/Landing#292]
<img width="1415" alt="image" src="https://github.com/LaurierHawkHacks/Landing/assets/11851551/2cbc06dc-9750-4e79-b7d1-ebee989e5af4">

Ideally, the "Meet the Team" banner should appear at the very top of the screen like this:
<img width="1436" alt="image" src="https://github.com/LaurierHawkHacks/Landing/assets/11851551/ae92e61b-7301-4787-a305-b677db65e207">

**Comment by teoh4770** [comment]
Thx
