### ISSUE TITLE
[Feature] Create Sponsors section

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#54]
- Sponsors are tiered (Gold, Silver, Bronze) based on their contribution
- Create the section so that:
- [ ] Gold tier sponsors display the biggest (relative to other sponsors)
- [ ] Silver tier sponsors display bigger (relative to other sponsors)
- [ ] Bronze tier sponsors display the smallest (relative to other sponsors)
- [ ] Each sponsor is an image that is clickable and links to their company page
- [ ] Each tier is on a different row
- [ ] Add an on hover effect with the sponsor's name (see https://2022.hawkhacks.ca/#sponsors)

**Comment by juancwu** [comment]
PR merged #71
