### ISSUE TITLE
[Refactor] Add MLH Code of Conduct & HawkHacks copyright to footer

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#56]
Link to MLH Code of Conduct:
https://static.mlh.io/docs/mlh-code-of-conduct.pdf

**Comment by teoh4770** [comment]
![Screenshot 2023-11-29 at 10 06 22 PM](https://github.com/LaurierHawkHacks/Landing/assets/98545971/8cfd5425-7a0e-4545-8a57-bf4a807619a9)

Something like this? @aidantrabs

**Comment by aidantrabs** [comment]
Yup exactly like that @teoh4770

**Comment by teoh4770** [comment]
![image](https://github.com/LaurierHawkHacks/Landing/assets/98545971/4546e816-f383-48bd-bede-514c23b74078)

Right now the footer looks like this. I asked the design team to improve the footer design, just in case they don't like how it looks.
