### ISSUE TITLE
[Fix] Convert any dynamic data to JSON data

### ISSUE THREAD

**Issue by aidantrabs** [LaurierHawkHacks/Landing#99]

**Comment by teoh4770** [comment]
since the team might change every year, we don't need to set it up  in firebase.
a json file should be enough.

**Comment by teoh4770** [comment]
I find it hard to export the database from notion for some reason @aidantrabs

**Comment by teoh4770** [comment]
can you help me check if you could export the database?

**Comment by aidantrabs** [comment]
will do in the morning
